### ISSUE TITLE
not an issue, but a question. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [FeignInt/dosbox-staging-deb#1]
whats this files are for?

**Comment by FeignInt** [comment]
hi Doommarine117
I have not uploaded anything yet
I've been tinkering with packaging dosbox-staging for debian
I will upload what I have soon

I'm using git-buildpackage with git-pbuilder(cowbuilder) to build the packages based on tags. i.e. this 'branch' will only contain the debian/ tree

```
for i in sid bullseye buster
do
    gbp buildpackage --git-force-create \
        --git-pbuilder \
        --git-overlay \
        --git-dist=$i  \
        --git-export-dir=../builds/${i} \
        --git-export=0.75.1-1 || break
done
```
would build v0.75.1 for sid, bullseye and buster 

I have crafted debian/rules such that it will output uniquely named deb files for the distro target.
I have Ubuntu Bionic version building as well, however I did need to drop the debhelper compatibility version to get that working, something I'm not thrilled about that since compat 11 is not recommended ( although the 'bug' is related to features not used in the dosbox-staging package )

do you use Debian or any of its derivatives such as ubuntu, mint etc.?
 
I'll try and get something uploaded soon, I just want to go back and tidy things up a bit,  I also need to upload my ssh/gpg keys
I'm also going to need to write some quickstart instructions

**Comment by DOOMMARINE117** [comment]
> 
> 
> hi Doommarine117
> I have not uploaded anything yet
> I've been tinkering with packaging dosbox-staging for debian
> I will upload what I have soon
> 
> I'm using git-buildpackage with git-pbuilder(cowbuilder) to build the packages based on tags. i.e. this 'branch' will only contain the debian/ tree
> 
> ```
> for i in sid bullseye buster
> do
>     gbp buildpackage --git-force-create \
>         --git-pbuilder \
>         --git-overlay \
>         --git-dist=$i  \
>         --git-export-dir=../builds/${i} \
>         --git-export=0.75.1-1 || break
> done
> ```
> 
> would build v0.75.1 for sid, bullseye and buster
> 
> I have crafted debian/rules such that it will output uniquely named deb files for the distro target.
> I have Ubuntu Bionic version building as well, however I did need to drop the debhelper compatibility version to get that working, something I'm not thrilled about that since compat 11 is not recommended ( although the 'bug' is related to features not used in the dosbox-staging package )
> 
> do you use Debian or any of its derivatives such as ubuntu, mint etc.?
> 
> I'll try and get something uploaded soon, I just want to go back and tidy things up a bit, I also need to upload my ssh/gpg keys
> I'm also going to need to write some quickstart instructions

cool. i look forward to those files. 

will i need to replace my files with tehse or justa dd these onto when they get loaded?

**Comment by FeignInt** [comment]
dd would be an odd way to install things in most circumstances
No, these will be debian packages intended to be installed via package manager,
I plan to include a branch which acts as an  apt-repo
It would involve adding a  source.list e.g. ```/etc/apt/sources.list.d/dosbox-staging.list```
then, 
```
sudo apt update && sudo apt upgrade # make sure everthinbg is up-to-date
sudo apt install dosbox-staging # install dosbox-staging
sudo apt autoremove # remove the sdl1.2 packages if nothing else is using them
```
That will remove, if installed, Debian's official dosbox package  and install dosbox-staging, including any missing dependencies.

But those who prefer to use a GUI package manager can install from that
I don't know if there is any appetite for these package files
Prior to packaging I was  just scripting  a
```
#insert export  CFLAGS here
./configure && make && strip -v -d src/dosbox -o ~/bin/dosbox-sdl2
```
then I quickly decided there was no point keeping the original dosbox around

anyway, I wouldn't get too excited there are no changes to the code
( well, just one cosmetic change pointing to a file location )
and thus far only default compiler flags.

It is more of a convenance than anything else
no stressing over manually installing dependencies, which can hang around orphaned if no longer needed ( tip,  "man apt-mark" ) 

if it is adopted upstream it would mean people could get updates automagically via there routine upgrades.
A separate "alpha" repo could host alpha builds for those who like to hunt down bugs.
But like I said I don't know what the appetite would be, or which distros most people are using. Ideally everyone is using Debian Sid :D
